CREATE TABLE ACCIDENT 
	(
		ID NUMBER(38),
		ACCIDENT_ADDRESS VARCHAR2(4000) NOT NULL,
		ACCIDENT_DATE DATE NOT NULL,
		CONSTRAINT PK_ACCIDENT PRIMARY KEY (ID)
	);
	
CREATE SEQUENCE ACCIDENT_SEQ
START WITH 0
MINVALUE 0;


CREATE TABLE CREATOR_INFO
	(
		ACCIDENT_ID NUMBER(38),
		NAME VARCHAR2(255),
		PHONE_NUMBER VARCHAR2(12) NOT NULL,
		OTHER_CONTACTS VARCHAR2(1000),
		CONSTRAINT FK_CREATOR_INFO FOREIGN KEY (ACCIDENT_ID) REFERENCES ACCIDENT (ID),
		CONSTRAINT PK_CREATOR_INFO PRIMARY KEY (ACCIDENT_ID)
	);
	
CREATE SEQUENCE CREATOR_INFO_SEQ
START WITH 0
MINVALUE 0;
	
CREATE TABLE MEDIA_PROOF
	(
		ID NUMBER(38),
		ACCIDENT_ID NUMBER(38) NOT NULL,
		PROOF BLOB,
		CONSTRAINT PK_MEDIA_PROOF PRIMARY KEY (ID),
		CONSTRAINT FK_MEDIA_PROOF FOREIGN KEY (ACCIDENT_ID) REFERENCES ACCIDENT (ID)
	);
	
CREATE SEQUENCE MEDIA_PROOF_SEQ
START WITH 0
MINVALUE 0;
	
CREATE TABLE TEXT_PROOF
	(
		ACCIDENT_ID NUMBER(38),
		PROOF VARCHAR2(4000) NOT NULL,
		CONSTRAINT FK_TEXT_PROOF FOREIGN KEY (ACCIDENT_ID) REFERENCES ACCIDENT (ID),
		CONSTRAINT PK_TEXT_PROOF PRIMARY KEY (ACCIDENT_ID)
	);
	
CREATE SEQUENCE TEXT_PROOF_SEQ
START WITH 0
MINVALUE 0;