DROP SEQUENCE MEDIA_PROOF_SEQ;

DROP SEQUENCE TEXT_PROOF_SEQ;

DROP SEQUENCE CREATOR_INFO_SEQ;

DROP SEQUENCE ACCIDENT_SEQ;

DROP TABLE MEDIA_PROOF;

DROP TABLE TEXT_PROOF;

DROP TABLE CREATOR_INFO;

DROP TABLE ACCIDENT;