SELECT * FROM ACCIDENT A	
	JOIN TEXT_PROOF T
		ON (A.ID = T.ACCIDENT_ID)
	JOIN CREATOR_INFO C
		ON (A.ID = C.ACCIDENT_ID)
	JOIN MEDIA_PROOF M
		ON (A.ID = M.ACCIDENT_ID);
		
		
SELECT * FROM ACCIDENT A	
	JOIN TEXT_PROOF T
		ON (A.ID = T.ACCIDENT_ID)
	JOIN CREATOR_INFO C
		ON (A.ID = C.ACCIDENT_ID);
		
		
SELECT * FROM ACCIDENT A
	JOIN MEDIA_PROOF M
		ON (A.ACCIDENT_ID = M.PROOF_ID);
		
		