SELECT * FROM ACCIDENT A	
	JOIN TEXT_PROOF T
		ON (A.ID = T.ACCIDENT_ID)
	JOIN CREATOR_INFO C
		ON (A.ID = C.ACCIDENT_ID)
	JOIN MEDIA_PROOF M
		ON (A.ID = M.ACCIDENT_ID);
		
		
SELECT * FROM ACCIDENT A	
	JOIN TEXT_PROOF T
		ON (A.ID = T.ACCIDENT_ID)
	JOIN CREATOR_INFO C
		ON (A.ID = C.ACCIDENT_ID);
		
		
SELECT * FROM ACCIDENT A
	JOIN MEDIA_PROOF M
		ON (A.ID = M.ACCIDENT_ID);
	
	SELECT * FROM ACCIDENT WHERE ACCIDENT_ADDRESS = 'mira street'
	
	SELECT * FROM ACCIDENT a WHERE a.ACCIDENT_ADDRESS = 'novomytishinsky prospect' AND a.ACCIDENT_DATE like TO_DATE(20181221, 'YYYY-MM-DD')
	
	
	SELECT * FROM ACCIDENT a WHERE a.ACCIDENT_ADDRESS = 'mira street' AND a.ACCIDENT_DATE BETWEEN TO_DATE(20181221, 'YYYY-MM-DD') AND TO_DATE(20181222, 'YYYY-MM-DD')
	
	SELECT * FROM ACCIDENT A
	
	SELECT * FROM MEDIA_PROOF
	
	SELECT * FROM TEXT_PROOF
	
	
		
		